language: R
sudo: false
cache:
  packages: true
  
addons:
  apt:
    packages:
      - libxml2-dev

r_packages:
  - covr
  - readr
  - ggplot2

install:
- R -e 'devtools::install_deps(dep = T)'

script:
- travis_wait 20 R CMD build .
- travis_wait 20 R CMD check *tar.gz

after_success:
  - Rscript -e 'library(covr); codecov()'
