language: R
sudo: false
cache:
  packages: true
  
addons:
  apt:
    packages:
      - libxml2-dev

r_packages:
  - covr
  - readr
  - ggplot2
  - devtools

install:
  - R -e "install.packages('devtools'); devtools::install_deps(dep = T)"

script:
  - travis_wait 30 R CMD build .
  - travis_wait 30 R CMD check *tar.gz

after_success:
  - travis_wait 30 Rscript -e 'library(covr); codecov()'
