language: R
sudo: false
cache:
  packages: true

script:
  - R CMD build . --no-staged-install
  
addons:
  apt:
    packages:
      - libxml2-dev

r_packages:
  - covr
  - readr
  - ggplot2

after_success:
  - Rscript -e 'library(covr); codecov()'
