---
title: "Entendendo os parâmetros utilizados na função fetch_proposicao()"
author: "Paulo Vinícius Soares"
date: "1 de novembro de 2017"
output: html_document
---

Na versão 0.2.0 do `rcongresso`, a função `fetch_proposicao()` agora dá suporte à consultas mais complexas utilizando o endpoint `/proposicoes`. Para mais detalhes, visite a página dos [Dados Abertos](https://dadosabertos.camara.leg.br/swagger/api.html).

A _query_ da consulta possui os seguintes parâmetros:

- `id`: Numeração única utilizada para identificar as proposições.
- `siglaUfAutor`: Sigla do estado do autor da proposição.
- `siglaTipo`: Sigla do tipo da proposição, por exemplo PEC, REQ, PL, PLP, entre outros.
- `siglaPartidoAutor`: Sigla do partido do auto da proposição, por exemplo DEM, PMDB, PT, entre outros.
- `numero`: Número da proposição. Por exemplo, se quisessemos buscar pela proposição PEC 182/2007, o parâmetro `número` dessa busca seria 182.
- `ano`: Ano em que a proposição foi apresentada.
- `dataApresentacaoInicio`: Data a partir da qual eu quero ver todas as proposições que foram apresentadas. Por exemplo, se quisessemos buscar as proposições que foram apresentadas a partir do dia 21/10/2005, o parâmetro `dataApresentacaoInicio` dessa busca seria _21/10/2005_.
- `dataApresentacaoFim`: Data cujas proposições retornadas na busca foram apresentadas até este dia. Por exemplo, se quisessemos buscar as proposições que foram apresentadas até o dia 10/12/2010, o parâmetro `dataApresentacaoFim` dessa busca seria _10/12/2010_.

Observe que os parâmetros `dataApresentacaoInicio` e `dataApresentacaoFim` podem atuar em conjunto estabelecendo um intervalo de tempo para a busca de proposições.

- `dataInicio`: 
- `dataFim`:
- `idAutor`:
- `autor`:
- `idSituacao`:
- `codPartido`:
- `pagina`:
- `itens`:

